"""favourites table

Revision ID: 04131f30ecc4
Revises: 
Create Date: 2020-10-03 21:25:39.773998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04131f30ecc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kitty_name', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites_table')
    # ### end Alembic commands ###
