"""favourites table relationship

Revision ID: 0f1e3833ab1c
Revises: 04131f30ecc4
Create Date: 2020-10-03 21:28:38.137877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1e3833ab1c'
down_revision = '04131f30ecc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites_table', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favourites_table', 'users_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites_table', type_='foreignkey')
    op.drop_column('favourites_table', 'user_id')
    # ### end Alembic commands ###
