"""empty message

Revision ID: c5cd7a4bff20
Revises: fb967351d1a0
Create Date: 2020-10-05 11:15:26.259868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cd7a4bff20'
down_revision = 'fb967351d1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites_table', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites_table', sa.Column('photo', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
