"""empty message

Revision ID: ef9667ff3016
Revises: c104aa6d5249
Create Date: 2020-10-03 22:23:05.611424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9667ff3016'
down_revision = 'c104aa6d5249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kitty_name', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites_table')
    # ### end Alembic commands ###
