"""empty message

Revision ID: fb967351d1a0
Revises: 88b28dfc25a7
Create Date: 2020-10-05 11:14:29.726700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb967351d1a0'
down_revision = '88b28dfc25a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites_table', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites_table', sa.Column('photo', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
